cp .Xmodmap ~/.Xmodmap
cp .fehbg ~/.fehbg
cp .bashrc ~/.bashrc
cp .condarc ~/.condarc
cp alacritty.toml ~/.config/alacritty/alacritty.toml
cp dunstrc ~/.config/dunst/dunstrc
cp i3-scrot.conf ~/.config/i3-scrot.conf
cp init.vim ~/.config/nvim/init.vim
cp coc-settings.json ~/.config/nvim/coc-settings.json
cp pcmanfm.conf ~/.config/pcmanfm/default/pcmanfm.conf
cp pcmanfm.config ~/.config/pcmanfm/default/pcmanfm.config
cp picom.conf ~/.config/picom.conf
cp config.ini ~/.config/polybar/config.ini
cp config.rasi ~/.config/rofi/config.rasi
cp .vimrc ~/.vimrc
cp bars ~/ponder/bars
cp keyboard.sh ~/ponder/keyboard.sh
cp rofi-start ~/ponder/rofi-start
cp pixel-lock ~/ponder/pixel-lock
cp .bashalias ~/ponder/.bashalias
cp config ~/.i3/config
